

# Site settings
title: coding
email: phoenix.fy24h@gmail.com
description: "welcome"
baseurl: ""
url: "http://www.fy24h.com"
auto: true

# Build settings
markdown: rdiscount
permalink: pretty
#permalink: /:year-:month/:title/
#pygments: false
paginate: 5 