#
# Blog Settings
#
author: Phoenix Huang
description: Think coding and you like it
url: http://www.fy24h.com
title: Think coding
subtitle: ...and you like it
gravatar_url: https://avatars1.githubusercontent.com/u/1182708?v=2&s=40
subscribe_rss: http://feeds.fy24h.com

# Github repositories
github_user: fy24h
github_repo_url: https://github.com/fy24h

# Twitter
twitter_user: haacked
twitter_tweet_button: false

# Disqus Comments
disqus_short_name: thinkcoding
disqus_show_comment_count: true

# Google Analytics
#google_analytics_tracking_id: UA-6869305-3


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
